### ISSUE TITLE
Build error on gcc-6.1.1

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/mrisim#1]
Exposed in fedora24 travis builds:  gcc-c++-6.1.1-3.fc24.x86_64

```
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
 };
 ^
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:47:1: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:75:16: error: narrowing conversion of ‘18446744073709551615ul’ from ‘long unsigned int’ to ‘double’ inside { } [-Wnarrowing]
       1.0, 1.0 };
                ^
/home/travis/rpmbuild/BUILD/minc-toolkit-v2-1.9.10/mrisim/src/minc/mincfile.cxx:75:16: error: narrowing conversion of ‘9223372036854775807l’ from ‘long int’ to ‘double’ inside { } [-Wnarrowing]
mrisim/CMakeFiles/mrisim.dir/build.make:151: recipe for target 'mrisim/CMakeFiles/mrisim.dir/src/minc/mincfile.cxx.o' failed
```

**Comment by gdevenyi** [comment]
works on gcc-c++-6.1.1-4.fc25.x86_64 on rawhide

I presume the issue is that something was made "too strict" in the fedora24 gcc release.

**Comment by gdevenyi** [comment]
Spoke too soon, fails on fedora rawhide with the same error

**Comment by gdevenyi** [comment]
bumping into this again with current minc-toolkit-v2 master HEAD

**Comment by gdevenyi** [comment]
Fixed
